backend:
  name: git-gateway
  repo: whoisgina/dat-foundation-website
  branch: master

publish_mode: editorial_workflow
media_folder: 'site/.vuepress/public/images'
public_folder: '/images'

collections:
  - name: 'blog' 
    label: 'Blog' 
    folder: 'site/blog/posts'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path_date_field: "date"
    fields: 
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Excerpt', name: 'excerpt', widget: 'markdown', hint: 'This displays on the blog index page and as the subhead of the blog post.', required: false}
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        searchFields: ["title"]
        multiple: true
        valueField: "title"
        displayFields: ["title"]
        required: false
      - label: "Authors"
        name: "authors"
        widget: "relation"
        collection: "people"
        searchFields: ["name"]
        multiple: true
        valueField: "name"
        displayFields: ["name"]
        required: false
      - label: 'Publish date'
        name: 'date'
        widget: 'datetime'
        default: ''
        format: 'YYYY-MM-DD'
      - {label: 'Image', name: 'image', widget: 'image', required: false }
      - {label: 'Featured', name: 'featured', widget: 'boolean', hint: 'If set to featured, the full blog post card is displayed on the blog index.', required: false}
      - {label: "Template", name: "template", widget: "hidden", default: "blog"}

  # Globals
  - name: globals
    label: Globals
    files:
      - file: site/_data/globals/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string, required: false, hint: 'Leave this blank if this item has no landing page or children.'}
              - label: Secondary items
                name: secondary
                widget: list
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Path, name: path, widget: string}
      - file: site/_data/globals/values.yml
        label: Values
        name: values
        fields: 
          - label: Values
            name: values 
            widget: list 
            fields: 
                - {label: Name, name: name, widget: string}
                - {label: Description, name: description, widget: markdown}
      - file: site/_data/globals/mission-statement.yml
        label: Mission Statement
        name: missionStatement
        fields: 
          - {label: Mission Statement, name: missionStatement, widget: markdown}

  # Collections
  - label: 'People'
    name: 'people'
    identifier_field: 'name'
    folder: 'site/_data/people'
    create: true
    slug: "{{name}}"
    fields: 
      - {label: 'Name', name: 'name', widget: 'string', hint: 'First and last name; required.', required: true}
      - {label: 'Title', name: 'title', widget: 'string', required: false}
      - label: 'Affiliation'
        name: 'affiliation'
        widget: 'object'
        required: false
        fields: 
          - {label: 'Organization or company name', name: 'name', widget: 'string', required: false}
          - {label: 'URL', name: 'url', widget: 'string', required: false, pattern: ['^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/|dat:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$', hint: 'Must be a valid URL.'] }
      - {label: 'Bio', name: 'bio', widget: 'markdown', buttons: ['link'], required: false}    
      - {label: 'Active', name: 'active', widget: 'boolean', hint: 'If set to active, the full bio is displayed.', required: false}
      - {label: 'Image', name: 'image', widget: 'image', required: false }
      - {label: 'Website', name: 'website', widget: 'string', required: false, hint: 'If this is present, both image and name will link there.', pattern: ['^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/|dat:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$', hint: 'Must be a valid URL.']}
  - label: 'Projects'
    name: 'projects'
    identifier_field: 'name'
    folder: site/_data/projects
    create: true
    slug: "{{name}}"
    fields: 
      - {label: 'Name', name: 'name', widget: 'string', required: true}
      - {label: 'Description', name: 'description', widget: 'markdown', buttons: ['link'], required: true}
      - {label: 'Image', name: 'image', widget: 'image', required: false }
      - {label: 'Website', name: 'website', widget: 'string', required: false, hint: 'If this is present, both image and name will link there.', pattern: ['^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/|dat:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$', hint: 'Must be a valid URL.']}
  - label: 'Tags'
    name: 'tags'
    identifier_field: 'name'
    folder: site/_data/projects
    create: true
    slug: "{{name}}"
    fields: 
      - {label: 'Name', name: 'name', widget: 'string', required: true}

  # Pages
  - label: 'About'
    name: 'about'
    files:    
      - label: 'People'
        name: 'People'
        file: 'site/_data/about/people.yml'
        fields:
          - {label: Title, name: title, widget: string}
          - label: 'Sections'
            name: 'section'
            widget: 'list'
            fields:
              - {label: Section Name, name: name, widget: string}
              - {label: 'Description', name: 'description', widget: 'markdown', buttons: ['link']}   
              - label: "People"
                name: "people"
                widget: "relation"
                collection: "people"
                searchFields: ["name"]
                multiple: true
                valueField: "name"
                displayFields: ["name"]
              
      - label: 'Financial'
        name: 'financial'
        file: 'site/about/financial/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Introduction, name: intro, widget: markdown}
          
      - label: 'Foundation'
        name: 'foundation'
        file: 'site/_data/about/foundation.yml'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Introduction, name: intro, widget: markdown}
          - label: 'Projects'
            name: 'projects'
            widget: 'list'
            fields:
              - {label: 'Name', name: 'name', widget: 'string', hint: 'The name of the project.', required: true}
              - {label: 'Logo', name: 'logo', widget: 'image', hint: '350 x 150 max.' }
              - {label: 'Website', name: 'website', widget: 'string', required: false, hint: 'If this is present, the logo will link here.', pattern: ['^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/|dat:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$', hint: 'Must be a valid URL.']}
              - {label: 'Description', name: 'description', widget: 'markdown', buttons: ['link']}
          - label: 'Sponsors'
            name: 'sponsors'
            widget: 'list'
            fields:
              - {label: 'Name', name: 'name', widget: 'string', hint: 'The name of the sponsor.', required: true}
              - {label: 'Logo', name: 'logo', widget: 'image', hint: '350 x 150 max.' }
              - {label: 'Website', name: 'website', widget: 'string', required: false, hint: 'If this is present, the logo will link here.', pattern: ['^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/|dat:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$', hint: 'Must be a valid URL.']}
              - {label: 'Description', name: 'description', widget: 'markdown', buttons: ['link']}    
      - label: 'History'
        name: 'history'
        file: 'site/_data/about/history.yml'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Introduction, name: intro, widget: markdown}
          - label: 'Timeline items'
            name: 'timeline'
            widget: 'list'
            fields:
              - {label: 'Description', name: 'description', widget: 'markdown', buttons: ['link']}    
              - label: 'Month and year'
                name: 'date'
                widget: 'datetime'
                default: ''
                format: 'MMMM YYYY'
              - {label: 'Milestone', name: 'milestone', widget: 'boolean', hint: 'If set as a milestone the timeline item is displayed at a larger size.', required: false}
  - label: 'Learn'
    name: 'learn'
    files:    
      - label: 'Tutorials'
        name: 'tutorials'
        file: 'site/learn/tutorials/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Content', name: 'content', widget: 'markdown'}
      - label: 'Protocol'
        name: 'protocol'
        file: 'site/learn/protocol/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Content', name: 'content', widget: 'markdown'}

  - label: 'Community'
    name: 'community'
    files:    
      - label: 'Code of Conduct'
        name: 'code-of-conduct'
        file: 'site/about/coc/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Content, name: content, widget: markdown}
      - label: 'I want to help!'
        name: 'contribute'
        file: 'site/community/contribute/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Content', name: 'content', widget: 'markdown'}
      - label: 'Newsletter'
        name: 'newsletter'
        file: 'site/community/newsletter/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Content', name: 'content', widget: 'markdown'}
      - label: 'Chat'
        name: 'chat'
        file: 'site/community/chat/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Content', name: 'content', widget: 'markdown'}
      - label: 'Events'
        name: 'events'
        file: 'site/community/events/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Content', name: 'content', widget: 'markdown'}

  - label: 'Explore'
    name: 'explore'
    files:    
      - label: 'Projects'
        name: 'projects'
        file: 'site/explore/projects/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Introduction, name: intro, widget: markdown}
          - {label: Featured projects, name: featured, widget: markdown}
          - label: 'Projects'
            name: 'projects'
            widget: 'list'
            fields:
              - {label: 'Name', name: 'name', widget: 'string', hint: 'The name of the project.', required: true}
              - {label: 'Description', name: 'description', widget: 'markdown', hint: 'A short description, no longer than 200 characters.', required: true}
              - {label: 'Image', name: 'image', widget: 'image' }
              - {label: 'Website', name: 'website', widget: 'string', required: false, hint: 'If this is present, the logo will link here.', pattern: ['^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/|dat:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$', hint: 'Must be a valid URL.']}
              - label: "Tags"
                name: "tags"
                widget: "select"
                multiple: true
                options: ["node", "rust", "clang", "javascript", "art", "browser", "cli"]
      
      - label: 'Modules'
        name: 'modules'
        file: 'site/explore/modules/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Content', name: 'content', widget: 'markdown'}

      # Lower priority
      - label: 'Design'
        name: 'design'
        file: 'site/explore/design/index.md'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: 'Content', name: 'content', widget: 'markdown'}
